name: top
channels:
  - defaults
  - conda-forge
dependencies:
  - jupyter=1.0
  - matplotlib=3.1
  - numpy=1.18
  - pandas=1.0
  - python=3.8
  - ipython=7.12
  - oauth2client=4.1.3
  - gspread=3.6.0